# SWMAL Exercise

### MAL Group-Nr. 15
13-09-2025

| Name   | ID        |
|--------|-----------|                       
| John   | 202209849 |
| Khaled | 202307853 |
| Jahye  | 202309135 |

## Python Basics

### Modules and Packages in Python

Reuse of code in Jupyter notebooks can be done by either including a raw python source as a magic command

```python
%load filename.py
```
but this just pastes the source into the notebook and creates all kinds of pains regarding code maintenance.

A better way is to use a python __module__. A module consists simply (and pythonic) of a directory with a module init file in it (possibly empty) 
```python
libitmal/__init__.py
```
To this directory you can add modules in form of plain python files, say
```python
libitmal/utils.py
```
That's about it! The `libitmal` file tree should now look like
```
libitmal/
├── __init__.py
├── __pycache__
│   ├── __init__.cpython-36.pyc
│   └── utils.cpython-36.pyc
├── utils.py
```
with the cache part only being present once the module has been initialized.

You should now be able to use the `libitmal` unit via an import directive, like
```python
import numpy as np
from libitmal import utils as itmalutils

print(dir(itmalutils))
print(itmalutils.__file__)

X = np.array([[1,2],[3,-100]])
itmalutils.PrintMatrix(X,"mylabel=")
itmalutils.TestAll()
```

#### Qa Load and test the `libitmal` module

Try out the `libitmal` module from [GITMAL]. Load this module and run the function

```python
from libitmal import utils as itmalutils
itmalutils.TestAll()
```
from this module.

##### Implementation details

Note that there is a python module ___include___ search path, that you may have to investigate and modify. For my Linux setup I have an export or declare statement in my .bashrc file, like

```bash
declare -x PYTHONPATH=~/ASE/ML/itmal:$PYTHONPATH
```
but your ```itmal```, the [GITMAL] root dir, may be placed elsewhere.

For ___Windows___, you have to add `PYTHONPATH` to your user environment variables...see screenshot below (enlarge by modding the image width-tag or find the original png in the Figs directory).

<img src="https://itundervisning.ase.au.dk/SWMAL/L01/Figs/Screenshot_windows_enviroment_variables.png" alt="WARNING: could not get image from server." style="height:250px" style="width:350px">

but notice that for this to take effect, you need to restart Anaconda or perhaps even reboot your Windows OS! An alternative, not requiring restart is to use a CMD prompt and the following command under Windows

```bash
CMD> setx.exe PYTHONPATH "C:\Users\auXXYYZZ\itmal"
```

replacing the username and path with whatever you have. Note that some Windows installations have various security settings enables, so that running `setx.exe` fails. Setting up a MAC should be similar to Linux; just modify your `PYTHONPATH` setting (still to be proven correct?, CEF). 


If everything fails you could programmatically add your path to the libitmal directory as

```python
import sys,os
sys.path.append(os.path.expanduser('~/itmal'))

from libitmal import utils as itmalutils
print(dir(itmalutils))
print(itmalutils.__file__)
```

For the journal: remember to document your particular PATH setup.

#### Qb Create your own module, with some functions, and test it

Now create your own module, with some dummy functionality. Load it and run you dummy function in a Jupyter Notebook.

Keep this module at hand, when coding, and try to capture reusable python functions in it as you invent them!

For the journal: remember to document your particular library setup (where did you place files, etc).

In [2]:
import sys
import os

sys.path.append(os.getcwd())
from mymodule import utils as myutils

print(f"Module location: {myutils.__file__}")

# Test functions
print("\nTesting my functions:")
print(myutils.say_hello("Omar"))
print(f"5 + 7 = {myutils.add_numbers(5, 7)}")

matrix = myutils.create_matrix(2, 3)
print(f"Created matrix:\n{matrix}")

# Run tests
myutils.test_my_functions()

print("\nSimple module works.")

Module location: d:\Uni\University-MachineLearning\L01\mymodule\utils.py

Testing my functions:
Hello Omar!
5 + 7 = 12
Created matrix:
[[1. 1. 1.]
 [1. 1. 1.]]
Testing my simple module:
Greeting: Hello ML Student!
Adding 5 + 3 = 8
Matrix:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

Simple module works.


#### Qc How do you 'recompile' a module?

When changing the module code, Jupyter will keep running on the old module. How do you force the Jupyter notebook to re-load the module changes? 

NOTE: There is a surprising issue regarding module reloads in Jupyter notebooks both using the browser interface and VSCode (at least with some Notebooks addons). If you use another development framework, like Spyder module reloading works out-of-the-box. 

In [ ]:
import importlib
import sys
import os

sys.path.append(os.getcwd())
from mymodule import utils as myutils

print("Before reload:")
print(myutils.say_hello("Test"))

# Method 1: importlib.reload() - most common
print("\nReloading module...")
myutils = importlib.reload(myutils)
print("After reload:")
print(myutils.say_hello("Test - Updated"))

# Method 2: Jupyter - automatic reloading
print("\nFor automatic reloading, use:")
print("%load_ext autoreload")
print("%autoreload 2")

%load_ext autoreload
%autoreload 2


Before reload:
Hello Test!

Reloading module...
My simple module loaded!
After reload:
Hello Test - Updated!

For automatic reloading, use:
%load_ext autoreload
%autoreload 2
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Why used:
```python
myutils = importlib.reload(myutils)
```
Explination: Used because you have to reassign the variable after reload for it to work.

#### [OPTIONAL] Qd Write a Howto on Python Modules a Packages

Write a short description of how to use modules in Python (notes on modules path, import directives, directory structure, etc.)

In [1]:
# Solution for Qd: Python Modules and Packages Howto

# Directory structure:
# mymodule/
#   __init__.py (makes it a package)  
#   utils.py (module with functions)

# Import methods:
import sys
import os
sys.path.append(os.getcwd())  # Add current directory to path
from mymodule import utils    # Import module

print("Module imported")
print("Functions:", [f for f in dir(utils) if not f.startswith('_')])

MyModule package loaded successfully!
My simple module loaded!
Module imported
Functions: ['add_numbers', 'create_matrix', 'np', 'say_hello', 'test_my_functions']


### Classes in Python

Good news: Python got classes. Bad news: they are somewhat obscure compared to C++ classes. 

Though we will not use object-oriented programming in Python intensively, we still need some basic understanding of Python classes. Let's just dig into a class-demo, here is `MyClass` in Python

```python
class MyClass:
   
    def myfun(self):
        self.myvar = "blah" # NOTE: a per class-instance variable.
        print(f"This is a message inside the class, myvar={self.myvar}.")

myobjectx = MyClass()
```

NOTE: The following exercise assumes some C++ knowledge, in particular the OPRG and OOP courses. If you are an EE-student, or from another Faculty, then ignore the cryptic C++ comments, and jump directly to some Python code instead. It's the Python solution here, that is important!

#### Qe Extend the class with some public and private functions and member variables

How are private function and member variables represented in python classes? 

What is the meaning of `self` in python classes?

What happens to a function inside a class if you forget `self` in the parameter list, like `def myfun():` instead of `def myfun(self):` and you try to call it like `myobjectx.myfun()`? Remember to document the demo code and result.


[OPTIONAL] What does 'class' and 'instance variables' in python correspond to in C++? Maybe you can figure it out, I did not really get it reading, say this tutorial

> https://www.digitalocean.com/community/tutorials/understanding-class-and-instance-variables-in-python-3

In [19]:
# Solution for Qe: Public/Private functions and self

class MyClass:
    def __init__(self):
        self.public_var = "public"        # Public variable
        self._protected_var = "protected" # Protected (convention)
        self.__private_var = "private"    # Private (name mangling)
    
    def public_method(self):
        """Public method"""
        return "This is public"
    
    def _protected_method(self):
        """Protected method (convention)"""
        return "This is protected"
    
    def __private_method(self):
        """Private method (name mangled)"""
        return "This is private"

# Test the class
obj = MyClass()

# What is 'self'?
print("'self' refers to the instance of the class")

# Test access from outside
print(f"Public: {obj.public_method()}")
print(f"Protected: {obj._protected_method()}")

# Private method access (will fail)
try:
    print(f"Private: {obj.__private_method()}")
except AttributeError as e:
    print(f"Private method error: {e}")

# What happens without 'self'?
class BadClass:
    def method_without_self():  # Missing self
        return "This will fail"

bad_obj = BadClass()
try:
    result = bad_obj.method_without_self()
except TypeError as e:
    print(f"Error without 'self': {e}")

'self' refers to the instance of the class
Public: This is public
Protected: This is protected
Private method error: 'MyClass' object has no attribute '__private_method'
Error without 'self': BadClass.method_without_self() takes 0 positional arguments but 1 was given


#### Qf Extend the class with a Constructor

Figure a way to declare/define a constructor (CTOR) in a python class. How is it done in python?

Is there a class destructor in python (DTOR)? Give a textual reason why/why-not python has a DTOR?

Hint: python is garbage collection like in C#, and do not go into the details of `__del__, ___enter__, __exit__` functions...unless you find it irresistible to investigate.

In [21]:
# Solution for Qf: Constructor and Destructor

class MyClassWithConstructor:
    def __init__(self, name, value=0):
        """Constructor - called when object is created"""
        self.name = name
        self.value = value
        print(f"Object {self.name} created with value {self.value}")
    
    def __del__(self):
        """Destructor - called when object is garbage collected"""
        print(f"Object {self.name} is being destroyed")

# Test constructor
obj1 = MyClassWithConstructor("test1", 42)
obj2 = MyClassWithConstructor("test2")

print(f"obj1.name: {obj1.name}, obj1.value: {obj1.value}")

# Python destructor notes:
print("\nPython has garbage collection:")
print("- __del__ is called when object is garbage collected")
print("- You rarely need to implement __del__")
print("- Python handles memory management automatically")

# Destructor called when objects go out of scope
obj1.__del__() 
print("obj1 deleted manually")

Object test1 created with value 42
Object test2 created with value 0
Object test2 is being destroyed
obj1.name: test1, obj1.value: 42

Python has garbage collection:
- __del__ is called when object is garbage collected
- You rarely need to implement __del__
- Python handles memory management automatically
Object test1 is being destroyed
obj1 deleted manually


#### Qg Extend the class with a to-string function

Then find a way to serialize a class, that is to make some `tostring()` functionality similar to a C++ 

```C++
friend ostream& operator<<(ostream& s,const MyClass& x)
{
    return os << ..
}
```

If you do not know C++, you might be aware of the C# way to string serialize
```
    string s=myobject.tostring()
```
that is a per-class buildin function `tostring()`, now what is the pythonic way of 'printing' a class instance?

In [3]:
# Solution for Qg: String representation (__str__ and __repr__)

class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def __str__(self):
        """String representation for users (readable)"""
        return f"{self.name}, {self.age} years old"
    
    def __repr__(self):
        """String representation for developers (unambiguous)"""
        return f"Person('{self.name}', {self.age})"

# Test string representations
person = Person("Alice", 25)

print("Using print() calls __str__:")
print(person)

print("\nUsing repr() calls __repr__:")
print(repr(person))

print("\nString conversion:")
print(f"str(person): {str(person)}")
print(f"repr(person): {repr(person)}")

# Without __str__, __repr__ is used as fallback
class SimpleClass:
    def __init__(self, value):
        self.value = value
    
    def __repr__(self):
        return f"SimpleClass({self.value})"

simple = SimpleClass(42)
print(f"\nWithout __str__, print uses __repr__: {simple}")

Using print() calls __str__:
Alice, 25 years old

Using repr() calls __repr__:
Person('Alice', 25)

String conversion:
str(person): Alice, 25 years old
repr(person): Person('Alice', 25)

Without __str__, print uses __repr__: SimpleClass(42)


#### [OPTIONAL] Qh Write a Howto on Python Classes 

Write a _How-To use Classes Pythonically_, including a description of public/privacy, constructors/destructors, the meaning of `self`, and inheritance.

In [ ]:
# TODO: Qh...

## Administration

REVISIONS||
:- | :- |
2018-12-19| CEF, initial.                  
2018-02-06| CEF, updated and spell checked. 
2018-02-07| CEF, made Qh optional.
2018-02-08| CEF, added PYTHONPATH for windows.
2018-02-12| CEF, small mod in itmalutils/utils.
2019-08-20| CEF, E19 ITMAL update.
2020-01-25| CEF, F20 ITMAL update.
2020-08-06| CEF, E20 ITMAL update, udpated figs paths.
2020-09-07| CEF, added text on OPRG and OOP for EE's
2020-09-29| CEF, added elaboration for journal in Qa+b.
2021-02-06| CEF, fixed itmalutils.TestAll() in markdown cell.
2021-08-02| CEF, update to E21 ITMAL.
2022-01-25| CEF, update to F22 SWMAL.
2022-02-25| CEF, elaborated on setx.exe on Windows and MAC PYTHONPATH.
2022-08-30| CEF, updated to v1 changes.
2022-09-16| CEF, added comment on module reloading when not using notebooks.
2023-08-30| CEF, minor table and text update.
2023-09-08| CEF, added not on Anaconda/Windows restart for PYTHON path env.
2023-02-18| CEF, elaborated on module reload and VSCode.